"""initial schema.

Revision ID: 9cdbb97ab0bb
Revises: 
Create Date: 2026-04-08 17:09:19.470526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cdbb97ab0bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('weather_data_city_key'), 'weather_data', type_='unique')
    op.create_unique_constraint('uq_user_city', 'weather_data', ['user', 'city'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_city', 'weather_data', type_='unique')
    op.create_unique_constraint(op.f('weather_data_city_key'), 'weather_data', ['city'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
