"""Change user string to user_id foreign key.

Revision ID: 07bb38931f0b
Revises: 9cdbb97ab0bb
Create Date: 2026-04-14 12:47:59.770448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bb38931f0b'
down_revision = '9cdbb97ab0bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dummy_model')
    op.drop_column('user', 'is_active')
    op.add_column('weather_data', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_user_city'), 'weather_data', type_='unique')
    op.create_unique_constraint('uq_user_city', 'weather_data', ['user_id', 'city'])
    op.create_foreign_key(None, 'weather_data', 'user', ['user_id'], ['id'])
    op.drop_column('weather_data', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('user', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'weather_data', type_='foreignkey')
    op.drop_constraint('uq_user_city', 'weather_data', type_='unique')
    op.create_unique_constraint(op.f('uq_user_city'), 'weather_data', ['user', 'city'], postgresql_nulls_not_distinct=False)
    op.drop_column('weather_data', 'user_id')
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('dummy_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dummy_model_pkey'))
    )
    # ### end Alembic commands ###
