"""empty message.

Revision ID: 05c449484016
Revises: fdc6fd73e276
Create Date: 2026-04-02 09:45:11.609764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c449484016'
down_revision = 'fdc6fd73e276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('longitude', sa.Integer(), nullable=False))
    op.add_column('weather_data', sa.Column('latitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_data', 'latitude')
    op.drop_column('weather_data', 'longitude')
    # ### end Alembic commands ###
