"""empty message.

Revision ID: b235f5ee12ad
Revises: 5d01a599cea1
Create Date: 2026-04-02 10:26:37.774415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b235f5ee12ad'
down_revision = '5d01a599cea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
