"""empty message.

Revision ID: 9f55c42d6a23
Revises: 2d99f86f9b35
Create Date: 2026-04-01 12:02:05.935218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f55c42d6a23'
down_revision = '2d99f86f9b35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
