"""empty message.

Revision ID: 81301e3b35e7
Revises: 05c449484016
Create Date: 2026-04-02 09:51:13.490455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81301e3b35e7'
down_revision = '05c449484016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_data', 'longitude',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('weather_data', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather_data', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('weather_data', 'longitude',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
