"""empty message.

Revision ID: 5d01a599cea1
Revises: 307d1f10fe82
Create Date: 2026-04-02 10:23:26.287568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d01a599cea1'
down_revision = '307d1f10fe82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('weather_data', sa.Column('latitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_data', 'latitude')
    op.drop_column('weather_data', 'longitude')
    # ### end Alembic commands ###
